apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kstreams-enricher
  name: kstreams-enricher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstreams-enricher
  template:
    metadata:
      labels:
        app: kstreams-enricher
    spec:
      containers:
      - name: kstreams-enricher
        image: quay.io/amqstreamsrhte2019/rhte-kstreams-enricher:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: APPLICATION_ID
            value: kstreams-enricher
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: USERNAME
            value: kstreams-enricher
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: kstreams-enricher
                key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"
